# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      networking:
        description: 'Run networking workflow'
        required: true
        type: boolean
        default: true
      adls:
        description: 'Run ADLS workflow'
        required: false
        type: boolean
        default: false
      adb:
        description: 'Run ADB workflow'
        required: false
        type: boolean
        default: false
      sql:
        description: 'Run SQL workflow'
        required: false
        type: boolean
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Networking workflow (required)
  networking:
    name: Networking Workflow
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # This workflow will always run since it's required
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.networking }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run networking tasks
        run: |
          echo "Running networking workflow"
          # Add your networking-specific tasks here
  
  # ADLS workflow (optional)
  adls:
    name: ADLS Workflow
    runs-on: ubuntu-latest
    # This workflow will only run if selected via inputs when manually triggered
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.adls }}
    needs: networking

    steps:
      - uses: actions/checkout@v4
      
      - name: Run ADLS tasks
        run: |
          echo "Running ADLS workflow"
          # Add your ADLS-specific tasks here

  # ADB workflow (optional)
  adb:
    name: ADB Workflow
    runs-on: ubuntu-latest
    # This workflow will only run if selected via inputs when manually triggered
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.adb }}
    needs: networking

    steps:
      - uses: actions/checkout@v4
      
      - name: Run ADB tasks
        run: |
          echo "Running ADB workflow"
          # Add your ADB-specific tasks here

  # SQL workflow (optional)
  sql:
    name: SQL Workflow
    runs-on: ubuntu-latest
    # This workflow will only run if selected via inputs when manually triggered
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.sql }}
    needs: networking

    steps:
      - uses: actions/checkout@v4
      
      - name: Run SQL tasks
        run: |
          echo "Running SQL workflow"
          # Add your SQL-specific tasks here
